### ISSUE TITLE
Generated link for the project does not work

### ISSUE THREAD

**Issue by shuyanzhou** [zeno-ml/zeno-client#43]
I found that the generated link for a newly created project leads to a 404 page. However, upon logging into my portal, I found that the project was successfully created.

e.g.
> Successfully created project.
Access your project at  https://hub.zenoml.com/project/my_name/my_project

<img width="518" alt="image" src="https://github.com/zeno-ml/zeno-client/assets/29911200/59c57ae5-30a0-4c38-8747-784c9c6cb034">

**Comment by Sparkier** [comment]
Thank you for reporting! Should be fixed with the next prod deploy, closing.
