### ISSUE TITLE
get_project() failing with APIError

### ISSUE THREAD

**Issue by mmaist** [zeno-ml/zeno-client#52]
Looks like the project-uuid is getting trimmed on both ends in get_project():
```
if response.status_code == 200:
            return ZenoProject(self.api_key, response.text[1:-1], self.endpoint)
```

 I don't think this should be necessary and is leading to this error.

**Comment by cabreraalex** [comment]
Thanks for this, we are investigating!

**Comment by mmaist** [comment]
This one was a mistake, upgrading python to 3.10.10 fixed it. I was on 3.9.13 for reference.
